/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { CS2Economy, CS2ItemType } from "@ianlucas/cs2-lib";

const CUSTOM_SKIN_CONTAINER_ID_PREFIX = 900000000;
const CUSTOM_SKIN_PAINT_INDEX_FACTOR = 100000;

function isWeaponOrKnife(type: string) {
  return type === CS2ItemType.Weapon || type === CS2ItemType.Melee;
}

function getWeaponNameFromDef(weaponDef: number) {
  const weapon =
    CS2Economy.itemsAsArray.find(
      (item) =>
        isWeaponOrKnife(item.type) &&
        item.def === weaponDef &&
        item.base === true &&
        !item.isStub()
    ) ??
    CS2Economy.itemsAsArray.find(
      (item) => isWeaponOrKnife(item.type) && item.def === weaponDef && !item.isStub()
    );

  if (weapon === undefined) {
    return undefined;
  }

  return weapon.name.split("|")[0]?.trim();
}

function getPaintNameFromIndex(paintIndex: number) {
  const paintedItem = CS2Economy.itemsAsArray.find(
    (item) =>
      isWeaponOrKnife(item.type) &&
      item.index === paintIndex &&
      item.name.includes("|")
  );

  if (paintedItem === undefined) {
    return `Paint ${paintIndex}`;
  }

  const parts = paintedItem.name.split("|").map((part) => part.trim());
  return parts.slice(1).join(" | ") || `Paint ${paintIndex}`;
}

export function encodeCustomSkinContainerId(
  weaponDef: number,
  paintIndex: number
) {
  return (
    CUSTOM_SKIN_CONTAINER_ID_PREFIX +
    weaponDef * CUSTOM_SKIN_PAINT_INDEX_FACTOR +
    paintIndex
  );
}

export function decodeCustomSkinContainerId(containerId?: number) {
  if (
    containerId === undefined ||
    containerId < CUSTOM_SKIN_CONTAINER_ID_PREFIX
  ) {
    return undefined;
  }

  const encoded = containerId - CUSTOM_SKIN_CONTAINER_ID_PREFIX;
  const weaponDef = Math.floor(encoded / CUSTOM_SKIN_PAINT_INDEX_FACTOR);
  const paintIndex = encoded % CUSTOM_SKIN_PAINT_INDEX_FACTOR;

  if (weaponDef < 0 || paintIndex < 0) {
    return undefined;
  }

  return {
    paintIndex,
    weaponDef
  };
}

export function isCustomSkinContainerId(containerId?: number) {
  return decodeCustomSkinContainerId(containerId) !== undefined;
}

export function getCustomSkinDisplayName(containerId?: number) {
  const metadata = decodeCustomSkinContainerId(containerId);
  if (metadata === undefined) {
    return undefined;
  }

  const model = getWeaponNameFromDef(metadata.weaponDef);

  if (model === undefined) {
    return undefined;
  }

  return {
    model,
    name: getPaintNameFromIndex(metadata.paintIndex)
  };
}

export function getCustomSkinPresentation(containerId?: number) {
  const metadata = decodeCustomSkinContainerId(containerId);
  if (metadata === undefined) {
    return undefined;
  }

  return {
    collectionName: "Custom Skin Collection",
    description:
      "This item was generated by applying a custom paint index to a weapon model.",
    flavor:
      "Built in the custom skin builder with cross-weapon paint application.",
    paintIndex: metadata.paintIndex,
    weaponDef: metadata.weaponDef
  };
}
